export type Specification = {
  label: string;
  value: string;
};

export type Product = {
  id: string;
  title: string;
  category: string;
  categoryLabel: string;
  price: string;
  image: string;
  images?: string[];
  order?: number;
  description: string;
  material: string;
  dimensions: string;
  origin: string;
  artisan: string;
  specifications?: Specification[];
};

export function resolveImageSrc(img?: string | null): string {
  if (!img || img.trim() === '') return '/placeholder.png';
  const trimmed = img.trim();
  if (/^https?:\/\//i.test(trimmed)) return trimmed;
  if (trimmed.startsWith('/')) return trimmed;
  return `/${trimmed}`;
}

export function getProductImageSrc(p: Product): string {
  return p.images?.[0] || p.image || '';
}

export function getProductImageUrl(p: Product): string {
  return resolveImageSrc(getProductImageSrc(p));
}

export function getProductImages(p: Product): string[] {
  const list = p.images && p.images.length > 0 ? p.images : p.image ? [p.image] : [];
  return list.length > 0 ? list : ['/placeholder.png'];
}

export const PRODUCTS: Product[] = [
  // ROGAN ART
  { id:'r1', title:'Peacock Rogan Canvas', category:'rogan-art', categoryLabel:'Rogan Art', price:'₹4,500', image:'images/rogan_1.png', description:'A breathtaking hand-painted masterpiece using the ancient Rogan art technique from Kutch, Gujarat. Each stroke is applied with castor-oil based paint on a stylus, never letting the tool touch the cloth. The peacock motif symbolises grace and beauty.', material:'Castor oil paint on black cloth', dimensions:'24" × 36"', origin:'Kutch, Gujarat', artisan:'Khatri Family Workshop' },
  { id:'r2', title:'Tree of Life Wall Hanging', category:'rogan-art', categoryLabel:'Rogan Art', price:'₹3,800', image:'images/rogan_2.png', description:'The Tree of Life depicted with meticulous detail — birds perch on flowering branches while intricate paisley borders frame the composition. A museum-quality piece for any home.', material:'Castor oil paint on dark cotton', dimensions:'18" × 28"', origin:'Nirona Village, Kutch', artisan:'Abdul Gafur Khatri' },
  { id:'r3', title:'Folk Dance Rogan Panel', category:'rogan-art', categoryLabel:'Rogan Art', price:'₹5,200', image:'images/rogan_3.png', description:'Vibrant dancing figures celebrate Gujarati folk tradition in this bold Rogan composition. The rhythmic repetition of human forms framed with floral borders reflects centuries of storytelling through craft.', material:'Castor oil paint on black velvet', dimensions:'30" × 20"', origin:'Kutch, Gujarat', artisan:'Khatri Master Artisans' },

  // LACQUERER ART
  { id:'l1', title:'Lacquered Jewellery Box', category:'lacquerer-art', categoryLabel:'Lacquerer Art', price:'₹2,200', image:'images/lacquer_1.png', description:'Hand-carved from lightweight wood and finished with layers of vibrant lacquer. Intricate floral motifs cover every surface, crafted by artisans who have inherited this technique across generations in Rajasthan.', material:'Lacquer on turned wood', dimensions:'20cm × 12cm × 8cm', origin:'Jaipur, Rajasthan', artisan:'Laad Bazaar Workshop' },
  { id:'l2', title:'Floral Lacquered Bowl', category:'lacquerer-art', categoryLabel:'Lacquerer Art', price:'₹1,800', image:'images/lacquer_2.png', description:'A stunning decorative bowl turned on a lathe and hand-coated with turquoise and gold lacquer. The delicate floral engravings are hand-carved after each layer dries, revealing gorgeous contrasting colours beneath.', material:'Lacquer on sheesham wood', dimensions:'22cm dia × 10cm height', origin:'Sawai Madhopur, Rajasthan', artisan:'Meena Craft Collective' },
  { id:'l3', title:'Lacquered Bangle Set', category:'lacquerer-art', categoryLabel:'Lacquerer Art', price:'₹950', image:'images/lacquer_3.png', description:'Traditional Rajasthani lac bangles, each coated in brilliant enamel colours with tiny embedded mirror and stone work. Worn as a symbol of auspiciousness, these are a staple of Indian bridal jewellery.', material:'Lac resin with mirror inlay', dimensions:'Set of 8, Size 2.6', origin:'Jaipur, Rajasthan', artisan:'Laad Market Artisans' },

  // BELL ART
  { id:'b1', title:'Brass Temple Bell', category:'bell-art', categoryLabel:'Bell Art', price:'₹1,500', image:'images/bell_1.png', description:'Cast using the lost-wax method, this solid brass temple bell carries a resonant pure tone. Adorned with deity relief carvings and floral engravings, it is as beautiful as it is sacred.', material:'Solid cast brass', dimensions:'18cm height, 12cm dia', origin:'Varanasi, UP', artisan:'Thathera Craft Community' },
  { id:'b2', title:'Copper Wind Chime Set', category:'bell-art', categoryLabel:'Bell Art', price:'₹2,800', image:'images/bell_2.png', description:'Seven hand-hammered copper bells suspended on twisted rope create the most melodious wind chime. Each bell is individually tuned and engraved with a different floral motif.', material:'Hand-hammered copper', dimensions:'65cm drop length', origin:'Moradabad, UP', artisan:'Peetal Nagar Artisans' },
  { id:'b3', title:'Copper Wind Chime Set', category:'bell-art', categoryLabel:'Bell Art', price:'₹2,800', image:'images/bell_3.png', description:'Seven hand-hammered copper bells suspended on twisted rope create the most melodious wind chime. Each bell is individually tuned and engraved with a different floral motif.', material:'Hand-hammered copper', dimensions:'65cm drop length', origin:'Moradabad, UP', artisan:'Peetal Nagar Artisans' },
  { id:'b4', title:'Copper Wind Chime Set', category:'bell-art', categoryLabel:'Bell Art', price:'₹2,800', image:'images/bell_4.png', description:'Seven hand-hammered copper bells suspended on twisted rope create the most melodious wind chime. Each bell is individually tuned and engraved with a different floral motif.', material:'Hand-hammered copper', dimensions:'65cm drop length', origin:'Moradabad, UP', artisan:'Peetal Nagar Artisans' },

  // LEATHER TOYS
  { id:'t1', title:'Painted Leather Horse', category:'leather-toys', categoryLabel:'Leather Toys', price:'₹1,200', image:'images/leather_toy_1.png', description:'A joyful hand-painted leather elephant crafted by Rajasthani artisans. Flowers, paisleys and geometric designs cover its body, applied by hand with natural pigments. A perfect decorative toy.', material:'Hand-painted natural leather', dimensions:'20cm × 15cm', origin:'Barmer, Rajasthan', artisan:'Mochi Community Crafts' },
  { id:'t2', title:'Leather Puppet Camel', category:'leather-toys', categoryLabel:'Leather Toys', price:'₹950', image:'images/leather_toy_2.png', description:'A spirited leather puppet horse adorned with vivid folk patterns. The articulated limbs allow posing, making it as fun as it is beautiful — a testament to Rajasthani leather artistry.', material:'Hand-painted vegetable-tanned leather', dimensions:'25cm × 18cm', origin:'Jodhpur, Rajasthan', artisan:'Rangila Leather Workshop' },
  { id:'t3', title:'Painted Leather Elephant', category:'leather-toys', categoryLabel:'Leather Toys', price:'₹1,200', image:'images/elephant.png', description:'A joyful hand-painted leather elephant crafted by Rajasthani artisans. Flowers, paisleys and geometric designs cover its body, applied by hand with natural pigments. A perfect decorative toy.', material:'Hand-painted natural leather', dimensions:'20cm × 15cm', origin:'Barmer, Rajasthan', artisan:'Mochi Community Crafts' },
  { id:'t4', title:'Painted Leather Elephant', category:'leather-toys', categoryLabel:'Leather Toys', price:'₹1,200', image:'images/horse.png', description:'A joyful hand-painted leather elephant crafted by Rajasthani artisans. Flowers, paisleys and geometric designs cover its body, applied by hand with natural pigments. A perfect decorative toy.', material:'Hand-painted natural leather', dimensions:'20cm × 15cm', origin:'Barmer, Rajasthan', artisan:'Mochi Community Crafts' },

  // SHOLA ART
  { id:'s1', title:'Shola Lotus Centrepiece', category:'shola-art', categoryLabel:'Shola Art', price:'₹3,200', image:'images/shola_1.png', description:'Crafted entirely from shola — a lightweight white sponge-wood — this elaborate lotus centrepiece demonstrates extraordinary Bengali Shola artisan skill. Every petal is individually cut and assembled.', material:'Shola (Indian cork wood)', dimensions:'35cm diameter', origin:'West Bengal', artisan:'Malakari Shilpa Sangha' },
  { id:'s2', title:'Shola Bird Figures', category:'shola-art', categoryLabel:'Shola Art', price:'₹1,800', image:'images/shola_2.png', description:'A flock of delicately crafted shola-wood birds, each with intricately textured wings and tail feathers. Pure white figurines that bring an ethereal serenity to any space.', material:'Shola pith wood', dimensions:'Set of 5, 8–14cm each', origin:'Bishnupur, West Bengal', artisan:'Pata Painters Cooperative' },

  // BIRD MAKING
  { id:'bm1', title:'Kingfisher Clay Sculpture', category:'bird-making', categoryLabel:'Bird Making', price:'₹2,500', image:'images/bird_1.png', description:'A stunningly lifelike kingfisher sculpted from terracotta clay and hand-painted with turquoise and russet plumage. Wire legs and hand-set glass eyes bring it to vivid life. Each piece is unique and signed.', material:'Terracotta clay, wire, glass eyes', dimensions:'22cm height', origin:'Kolkata, West Bengal', artisan:'Krishnanagar Clay Artists' },
  { id:'bm2', title:'Wire Peacock Sculpture', category:'bird-making', categoryLabel:'Bird Making', price:'₹3,400', image:'images/bird_2.png', description:'An awe-inspiring peacock crafted from twisted wire and natural iridescent feathers. The tail fans out in a spectacular display, each feather individually attached. A heirloom-quality piece.', material:'Galvanised wire, natural peacock feathers', dimensions:'45cm height, 60cm tail span', origin:'Rajasthan', artisan:'Vishwakarma Wire Craft Guild' },
  { id:'bm3', title:'Hoopoe Wooden Bird Sculpture', category:'bird-making', categoryLabel:'Bird Making', price:'₹2,800', image:'images/bird_3.png', description:'A beautifully hand-carved and painted Hoopoe bird in natural wood. The iconic crown feathers are delicately crafted and painted with warm earthy tones — a prized collector\'s piece capturing the spirit of India\'s avian heritage.', material:'Carved wood, natural pigments, wire claws', dimensions:'18cm height', origin:'Kondapalli, Andhra Pradesh', artisan:'Kondapalli Toy Makers' },
  { id:'bm4', title:'Green Warbler Wood Figurine', category:'bird-making', categoryLabel:'Bird Making', price:'₹2,200', image:'images/bird_4.png', description:'A charming hand-painted Green Warbler carved from soft wood. The vibrant yellow-green plumage with dark wing markings is rendered with extraordinary detail using layered natural dyes. A delightful addition to any nature-inspired décor.', material:'Softwood, mineral dyes, wire legs', dimensions:'10cm height', origin:'Channapatna, Karnataka', artisan:'Channapatna Toy Artisans' },
  { id:'bm5', title:'Red Munia Folk Bird', category:'bird-making', categoryLabel:'Bird Making', price:'₹3,100', image:'images/bird_5.png', description:'Handcrafted Red Munia bird with exquisite folk-art painted plumage in white, burgundy and copper tones. The intricate striped wing detailing is applied with a fine brush over multiple firing sessions. A celebration of Indian folk ornithology.', material:'Fired clay, mineral pigments, organic wire', dimensions:'14cm height', origin:'Bankura, West Bengal', artisan:'Bankura Horse Craft Village' },
  { id:'bm6', title:'Spotted Quail Clay Bird', category:'bird-making', categoryLabel:'Bird Making', price:'₹1,900', image:'images/bird_6.png', description:'A plump and endearing hand-sculpted Spotted Quail in terracotta. The signature spotted body and green-tinted wing scales are painted by hand using traditional techniques passed down through generations of Rajasthani artisans.', material:'Terracotta, natural earth pigments', dimensions:'12cm height', origin:'Molela, Rajasthan', artisan:'Molela Clay Craft Co-operative' },
  { id:'bm7', title:'Indian Shama Bird Sculpture', category:'bird-making', categoryLabel:'Bird Making', price:'₹3,800', image:'images/bird_7.png', description:'A striking hand-painted Indian Shama bird in deep cobalt blue and amber. Carved with precision to capture the bird\'s proud posture and characteristic fanned tail. The brushwork on the feathers demonstrates master-level artisanal skill.', material:'Carved hardwood, acrylic & lacquer finish', dimensions:'20cm height', origin:'Saharanpur, Uttar Pradesh', artisan:'Saharanpur Wood Craft Guild' },
  { id:'bm8', title:'Indian Shama Bird Sculpture', category:'bird-making', categoryLabel:'Bird Making', price:'₹3,800', image:'images/bird_8.png', description:'A striking hand-painted Indian Shama bird in deep cobalt blue and amber. Carved with precision to capture the bird\'s proud posture and characteristic fanned tail. The brushwork on the feathers demonstrates master-level artisanal skill.', material:'Carved hardwood, acrylic & lacquer finish', dimensions:'20cm height', origin:'Saharanpur, Uttar Pradesh', artisan:'Saharanpur Wood Craft Guild' },
  { id:'bm9', title:'Indian Shama Bird Sculpture', category:'bird-making', categoryLabel:'Bird Making', price:'₹3,800', image:'images/bird_9.png', description:'A striking hand-painted Indian Shama bird in deep cobalt blue and amber. Carved with precision to capture the bird\'s proud posture and characteristic fanned tail. The brushwork on the feathers demonstrates master-level artisanal skill.', material:'Carved hardwood, acrylic & lacquer finish', dimensions:'20cm height', origin:'Saharanpur, Uttar Pradesh', artisan:'Saharanpur Wood Craft Guild' },

  // LEATHER BAG
  { id:'lb1', title:'Hand-Tooled Tote Bag', category:'leather-bag', categoryLabel:'Leather Bag', price:'₹5,800', image:'images/bag_1.png', description:'A spacious hand-tooled leather tote from full-grain vegetable-tanned leather. Intricate floral and vine patterns are carved and stamped by hand — a process taking over 12 hours per bag. Sturdy brass hardware and hand-stitched seams ensure a lifetime of use.', material:'Full-grain vegetable-tanned leather, brass hardware', dimensions:'38cm × 28cm × 12cm', origin:'Kanpur, UP', artisan:'Chamar Artisan Collective' },
  { id:'lb2', title:'Embossed Ethnic Sling Bag', category:'leather-bag', categoryLabel:'Leather Bag', price:'₹4,200', image:'images/bag_2.png', description:'A handsome cross-body sling bag in rich chocolate-brown leather, embossed with geometric ethnic patterns inspired by Warli folk art. Adjustable strap, interior pockets and antique brass zip.', material:'Embossed cowhide leather, antique brass fittings', dimensions:'26cm × 18cm × 6cm', origin:'Dharavi, Mumbai', artisan:'Kohinoor Leather Craft' },
  { id:'lb3', title:'Rajasthani Mirror-Work Clutch', category:'leather-bag', categoryLabel:'Leather Bag', price:'₹2,600', image:'images/bag-3.png', description:'A stunning evening clutch in deep indigo leather adorned with hand-stitched mirror-work and thread embroidery in the Rajasthani tradition. Each tiny mirror is individually sewn on by artisans of the Thar desert communities, making every clutch truly one of a kind.', material:'Vegetable-tanned leather, glass mirrors, silk thread', dimensions:'28cm × 16cm × 4cm', origin:'Barmer, Rajasthan', artisan:'Desert Craft Women\'s Collective' },
  { id:'lb4', title:'Madhubani Painted Bucket Bag', category:'leather-bag', categoryLabel:'Leather Bag', price:'₹5,100', image:'images/bag-4.png', description:'A bold bucket bag hand-painted with vivid Madhubani folk motifs — fish, lotus and birds rendered in the distinctive black-outlined style of Mithila artisans. The natural leather canvas beautifully absorbs mineral pigments, creating an artwork you carry.', material:'Full-grain leather, mineral pigments, cotton lining', dimensions:'30cm × 30cm × 16cm', origin:'Madhubani, Bihar', artisan:'Mithila Art Cooperative' },
  { id:'lb5', title:'Kolhapuri Weave Shoulder Bag', category:'leather-bag', categoryLabel:'Leather Bag', price:'₹3,700', image:'images/bag-5.png', description:'Inspired by the iconic Kolhapuri sandal-making tradition, this shoulder bag features intricately woven leather strips in natural tan and chocolate tones. Each strip is hand-cut, soaked, and woven wet before drying into its final rigid yet supple form.', material:'Woven vegetable-tanned leather strips, iron ring hardware', dimensions:'34cm × 24cm × 10cm', origin:'Kolhapur, Maharashtra', artisan:'Garpure Charmkar Workshop' },
  { id:'lb6', title:'Block-Print Leather Backpack', category:'leather-bag', categoryLabel:'Leather Bag', price:'₹6,400', image:'images/bag_6.png', description:'A roomy everyday backpack in buttery soft leather, hand-decorated using wooden block printing — an art form more commonly seen on fabrics, here transferred onto leather with remarkable results. Ajrakh-style geometric repeat patterns cover the front panel entirely.', material:'Soft-grain leather, natural dye block prints, brass zips', dimensions:'40cm × 30cm × 14cm', origin:'Ajrakhpur, Kutch', artisan:'Khatri Block Print Studio' },
  { id:'lb7', title:'Dokra-Clasp Leather Pouch', category:'leather-bag', categoryLabel:'Leather Bag', price:'₹3,100', image:'images/bag8.png', description:'A compact and charming leather pouch fitted with a handcast Dokra-art brass clasp — the tribal lost-wax casting of Bastar, Chhattisgarh. The raw, burnished leather and the rustic brass clasp create a beautifully honest pairing that celebrates two distinct Indian craft forms.', material:'Burnished pull-up leather, cast brass Dokra clasp, jute lining', dimensions:'20cm × 14cm × 5cm', origin:'Bastar, Chhattisgarh & Kanpur, UP', artisan:'Bastar Brass Guild & Chamar Collective' },
  { id:'lb8', title:'Suede Patchwork Tote', category:'leather-bag', categoryLabel:'Leather Bag', price:'₹4,800', image:'images/bag9.png', description:'A cheerful oversized tote assembled from hand-dyed suede patches in earthy terracotta, saffron and forest green. Each patch is cut from offcuts salvaged from larger leather projects, making this bag an exercise in zero-waste craft. No two bags have the same patchwork configuration.', material:'Hand-dyed suede offcuts, linen stitching, wooden toggles', dimensions:'42cm × 36cm × 8cm (open)', origin:'Hyderabad, Telangana', artisan:'Secunderabad Leather Artisans Guild' }
];
